version: '3'
services:

  home:
    build: './home'
    ports:
      - "3003:3000"
  login:
    build: './login-register/loginRegister'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb+srv://Amartya:p2GQJ4dSGw4AI3Lf@cluster0.ppvul.mongodb.net

  jobs:
    build: './jobsapplied/jobsApplied'
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb+srv://Amartya:p2GQJ4dSGw4AI3Lf@cluster0.ppvul.mongodb.net

  nginx:
     restart: always
     build:
        context: ./nginx
     ports:
       - "80:80"
  depends_on:
      - home
      - login
      - jobs
